version: '3.9'
services:
  mongo-server:
    image: mongo:latest
    container_name: mongo-server
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb_network
      
  mongo-client:
    image: mongo-express:latest
    container_name: mongo-client
    restart: always
    depends_on:
      - mongo-server
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-server
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - 8081:8081
    networks:
      - mongodb_network
volumes:
  mongodb_data:
networks:
  mongodb_network: